language: php

php:
- 7.1
- 7.2

env:
    matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

services:
- mysql

sudo: required

before_script:
- travis_retry composer self-update
- travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
- mysql -e 'CREATE DATABASE test_om;'
- wget https://repo.percona.com/apt/percona-release_0.1-5.trusty_all.deb
- sudo dpkg -i percona-release_0.1-5.trusty_all.deb
- sudo apt-get update
- sudo apt-get install -y percona-toolkit

script:
- vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover --configuration phpunit.xml.travis --testdox

after_script:
- php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
